"use client";

import { TopNav } from "@/components/chrome/TopNav";
import { SiteFooter } from "@/components/chrome/SiteFooter";
import { WizardCard } from "@/components/wizard/WizardCard";
import { WizardHeader } from "@/components/wizard/WizardHeader";
import { BtnPrimary } from "@/components/ui/BtnPrimary";
import { BtnOutline } from "@/components/ui/BtnOutline";
import { ASSETS } from "@/lib/assets";
import { WIZARD_ACTIONS, getOnboardingCopy } from "@/lib/data/onboarding";
import { serviceRoutes, type ServiceConfig } from "@/lib/data/service-config";
import { useDemoState } from "@/lib/demo-state";

/*
 * PP-08 — Other verification. Figma 6217:35183
 * `StudentAidNL_Prerequisite check_03`, 1440 x 1030.215. NEW 2026-09-28.
 *
 * FLOW B ONLY. It exists for services with `otherVerificationStep: true` —
 * the route is generated by src/app/services/[serviceId]/other-verification/
 * from `otherVerificationParams()`, which today names `studentaid` alone. It
 * sits between the method step (PP-07) and the CertifiO ID hand-off (PP-09).
 *
 * Geometry, verbatim from get_metadata on 6217:35183 and get_design_context on
 * 6217:35197 / 6217:35200 (read 2026-09-28, read-only):
 *   top-nav actions    1440 x 69       at y=0
 *   Main Content       1440 x 821      at y=69      (6217:35185)
 *     wizard-card       820 x 517      at x=310, y=152   p-[40px] gap-[32px]
 *       wizard-header   740 x 118      at y=40    step-bar 16, fill 555 (75%),
 *                                                 "Prerequisite Check" bold
 *       section-intro   740 x 54       at y=190   "Other verification" 36px Bold
 *       Frame 1         740 x 114      at y=276   (6217:35200)
 *         service-details 620 x 114 (h PINNED, content is 56)
 *           service-title-row  gap-[12px], items-start
 *             Frame 14674  pt-[4px] -> radio-outer 16 x 16, radio-inner 8 x 8
 *                          SHOWN (i.e. selected)
 *             verification-list-wrapper  gap-[8px]
 *               6217:35234  16px Regular #5f6368, leading 1.5
 *               6217:35237  16px Regular #5f6368, leading 1.5
 *       actions-row     740 x 55       at y=422   pt-[16px], justify-end
 *         Cancel 6217:35241  hidden="true" -> NOT RENDERED
 *         btn-back 75 x 39, ContinueButton 114 x 39
 *   footer verified    1440 x 140.215  at y=890
 * 40 + 118 + 32 + 54 + 32 + 114 + 32 + 55 + 40 = 517, and 152 + 517 + 152 = 821.
 *
 * THE 114px BOX IS REPRODUCED AS A MINIMUM, not a fixed height. Figma pins
 * service-details at 114 around 56px of content — that is what makes the card
 * 517 — so at 1440 `min-h-[114px]` draws the same box; below it the two lines
 * wrap to more and the box grows instead of clipping them.
 *
 * NO CANCEL. `Cancel` 6217:35241 is hidden="true" in Figma; hidden layers are
 * not part of the design and are not rendered (the rule every CID `Check box`
 * follows). §9 PP-08 agrees: "Buttons Back and Continue (no Cancel)".
 *
 * THE RADIO IS PRE-SELECTED AND IS THE ONLY OPTION, so it is not a control:
 * there is nothing to change it to. It is drawn with the same 16px
 * `radioSelected` asset NL-07 / PP-07 use, and exposed to assistive tech as a
 * checked radio in a one-item group so its state is announced, not just seen.
 *
 * EXITS — §9: "Continue -> PP-09".
 *   Back     -> /services/<id>/onboard/                  PP-07, the previous step
 *   Continue -> /cid/<id>/continue-on-mobile/            PP-09, this service's hand-off,
 *               recording `otherVerificationConfirmed` (§12.2) in `gnl-demo:v1`
 *
 * RESPONSIVE: the wizard's usual ladder — well 152 -> 96 -> 48 -> 32, heading
 * 36 -> 30 -> 26, actions a full-width stack below 480 with the primary on
 * top (`flex-col-reverse`, DOM order unchanged). The main is not pinned; the
 * 152px bottom pad keeps the symmetric well, as on Summary / Terms.
 *
 * "use client": Continue writes the acknowledgement into the store in its
 * click handler. Nothing is READ from the store during render, so there is no
 * hydration surface here — see src/lib/demo-state.tsx.
 */
export function OtherVerificationScreen({ service }: { service: ServiceConfig }) {
  const routes = serviceRoutes(service.id);
  const copy = getOnboardingCopy(service);
  const other = copy.otherVerification;
  const { patchService } = useDemoState();

  return (
    <div className="gnl-desktop-shell">
      <TopNav />

      {/* Main Content 6217:35185 */}
      <main className="w-full" data-node-id="6217:35185">
        <div className="gnl-gutter [--gnl-gutter:310px] flex justify-center pt-[152px] pb-[152px] max-xl:pt-[96px] max-xl:pb-[96px] max-md:pt-[48px] max-md:pb-[48px] max-xs:pt-[32px] max-xs:pb-[32px]">
          {/* wizard-card 6217:35186 */}
          <WizardCard>
            <WizardHeader title={copy.wizardTitle} current={2} size="lg" />

            {/* section-intro 6217:35197 — one child, so no gap is expressed. */}
            <div className="flex w-full shrink-0 flex-col items-start" data-node-id="6217:35197">
              <h1
                className="w-full shrink-0 text-[36px] font-bold leading-[1.5] text-[color:var(--gnl-heading,#212326)] [word-break:break-word] max-md:text-[30px] max-xs:text-[26px]"
                data-node-id="6217:35198"
              >
                {other.title}
              </h1>
            </div>

            {/* Frame 1 6217:35200 -> service-details 6217:35228 */}
            <div
              className="flex min-h-[114px] w-full shrink-0 flex-col items-start"
              data-node-id="6217:35200"
            >
              {/* service-title-row 6217:35229 */}
              <div
                className="flex w-full items-start gap-[12px]"
                role="radiogroup"
                aria-label={other.title}
                data-node-id="6217:35229"
              >
                {/* Frame 14674 6217:38164 — pt-[4px] seats the 16px radio on
                    the first 24px line. */}
                <div className="flex shrink-0 items-center pt-[4px]" data-node-id="6217:38164">
                  <div
                    className="relative size-[16px] shrink-0"
                    role="radio"
                    aria-checked="true"
                    aria-labelledby="pp08-option"
                    data-node-id="6217:35230"
                  >
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      alt=""
                      className="absolute inset-0 block size-full max-w-none"
                      src={ASSETS.radioSelected}
                    />
                  </div>
                </div>

                {/* verification-list-wrapper 6217:35233 */}
                <div
                  className="flex min-w-px flex-1 flex-col items-start gap-[8px]"
                  data-node-id="6217:35233"
                >
                  <p
                    id="pp08-option"
                    className="w-full text-[16px] font-normal leading-[1.5] text-[#5f6368] [word-break:break-word]"
                    data-node-id="6217:35234"
                  >
                    {other.option}
                  </p>
                  <p
                    className="w-full text-[16px] font-normal leading-[1.5] text-[#5f6368] [word-break:break-word]"
                    data-node-id="6217:35237"
                  >
                    {other.confirmation}
                  </p>
                </div>
              </div>
            </div>

            {/* actions-row 6217:35240 — Back + Continue, no Cancel (hidden in Figma). */}
            <div
              className="flex w-full shrink-0 items-center justify-end gap-[24px] pt-[16px] max-xs:flex-col-reverse max-xs:items-stretch max-xs:gap-[12px]"
              data-node-id="6217:35240"
            >
              <BtnOutline href={routes.onboard} className="max-xs:w-full max-xs:justify-center">
                {WIZARD_ACTIONS.backLabel}
              </BtnOutline>
              <BtnPrimary
                href={other.continueHref}
                size="lg"
                nodeId="6217:35244"
                className="max-xs:w-full"
                /*
                 * No `status` in the patch, on purpose: the same "only ever
                 * moves forward" rule as TrackStep. A presenter re-walking the
                 * wizard after finishing it must not demote an `onboarded`
                 * service back to `in_progress` with one click.
                 */
                onClick={() =>
                  patchService(service.id, {
                    step: "handoff",
                    method: "gnl_idv",
                    otherVerificationConfirmed: true,
                  })
                }
              >
                {WIZARD_ACTIONS.continueLabel}
              </BtnPrimary>
            </div>
          </WizardCard>
        </div>
      </main>

      <SiteFooter variant="desktop" />
    </div>
  );
}
